### ISSUE TITLE
Change the . into _

### ISSUE THREAD

**Issue by Chardonneaur** [Findus23/plugin-CustomiseTranslations#10]
Hello,
I think that due to the change from Transifex to Weblate, now the syntax of the language key is Actions_ColumnPageURL instead of Actions.ColumnPageURL
Hope that helps,

**Comment by Findus23** [comment]
Where do you see a dot suggested as a separator? I think this plugin since the beginning split the entered text on the underscore:
https://github.com/Findus23/plugin-CustomiseTranslations/blob/4.x-dev/MyCustomLoader.php#L19

**Comment by Chardonneaur** [comment]
Sorry I got confused, weblate is using the dot whereas it is an underscore to type.
